# Generated by Django 5.0.1 on 2026-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('licensee_name', models.CharField(blank=True, default='', max_length=256)),
                ('licensee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('order_id', models.CharField(blank=True, default='', max_length=64)),
                ('ls_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pdf_downloaded', models.BooleanField(default=False, help_text='True after licensee has downloaded the PDF at least once.')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
