# Generated by Django 5.0.1 on 2026-02-23 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=16, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('price_monthly', models.PositiveIntegerField(default=0)),
                ('max_file_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('max_text_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('max_expiry_days', models.PositiveIntegerField(blank=True, null=True)),
                ('clipboard_idle_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('clipboard_max_lifetime_days', models.PositiveIntegerField(blank=True, null=True)),
                ('anon_file_lifetime_days', models.PositiveIntegerField(blank=True, help_text='Hard ceiling (days from creation) for file drops with no explicit expiry. null = never expire (paid plans).', null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('renewals', models.PositiveIntegerField(blank=True, help_text='null = unlimited, 0 = none', null=True)),
                ('password_protection', models.BooleanField(default=False)),
                ('max_collections', models.PositiveIntegerField(blank=True, help_text='null = unlimited, 0 = none', null=True)),
                ('max_groups', models.PositiveIntegerField(blank=True, default=0, help_text='null = unlimited, 0 = none', null=True)),
                ('webhooks', models.BooleanField(default=False)),
                ('api_keys', models.PositiveIntegerField(blank=True, default=0, help_text='null = unlimited, 0 = none', null=True)),
                ('scheduled_drops', models.PositiveIntegerField(blank=True, default=0, help_text='null = unlimited, 0 = none', null=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the token. Never store plaintext.', max_length=256, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='First 8 chars of the token for identification.', max_length=8)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug — something is broken'), ('ui', 'UI — visual or layout issue'), ('perf', "Performance — it's slow"), ('feature', 'Feature request'), ('security', 'Security concern'), ('other', 'Other')], max_length=16)),
                ('description', models.TextField()),
                ('hide_identity', models.BooleanField(default=True)),
                ('github_issue_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(db_index=True, help_text='Unique @handle for the group.', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DropTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, default='', help_text='Default content for clipboard drops.')),
                ('burn', models.BooleanField(default=False)),
                ('expiry_days', models.PositiveIntegerField(blank=True, null=True)),
                ('password', models.BooleanField(default=False, help_text='Prompt for password when using this template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_templates', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_templates', to='core.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('public_inbox', models.BooleanField(default=False, help_text='Anyone can drop into this collection; only owner/members can read.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, help_text='Group that owns this collection (alongside or instead of user owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='core.group')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GroupInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('writer', 'Writer'), ('admin', 'Admin')], default='reader', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='null = unlimited, 1 = single-use', null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='core.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter ($3/mo)'), ('pro', 'Pro ($8/mo)')], default='free', max_length=16)),
                ('plan_since', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('storage_used_bytes', models.PositiveBigIntegerField(default=0)),
                ('ls_customer_id', models.CharField(blank=True, default='', help_text='Lemon Squeezy customer ID', max_length=64)),
                ('ls_subscription_id', models.CharField(blank=True, default='', help_text='Lemon Squeezy subscription ID', max_length=64)),
                ('ls_subscription_status', models.CharField(blank=True, default='', help_text='active, cancelled, expired, etc.', max_length=32)),
                ('notify_bug_fix', models.BooleanField(default=True, help_text='Send an email when a bug the user reported is fixed (GitHub issue closed).')),
                ('notify_product_updates', models.BooleanField(default=True, help_text='Changelog, new features, and product announcements.')),
                ('notify_billing', models.BooleanField(default=True, help_text='Payment receipts, failed charges, and plan change confirmations.')),
                ('is_test', models.BooleanField(db_index=True, default=False, help_text='Created by the integration test suite. Purged at deploy.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('ns', models.CharField(choices=[('c', 'Clipboard'), ('f', 'File')], default='c', max_length=1)),
                ('key', models.CharField(help_text='Drop key this alias points to.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='CollectionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(choices=[('c', 'Clipboard'), ('f', 'File')], max_length=1)),
                ('key', models.CharField(max_length=120)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.collection')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('collection', 'ns', 'key')},
            },
        ),
        migrations.CreateModel(
            name='FeatureVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='free=1, paid=3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.featureproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('proposal', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(choices=[('c', 'Clipboard'), ('f', 'File')], db_index=True, default='c', max_length=1)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('file', 'File')], max_length=4)),
                ('anon_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(blank=True, default='')),
                ('file_public_id', models.CharField(blank=True, default='', max_length=512)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('filesize', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_lifetime_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('burn', models.BooleanField(default=False, help_text='Delete after first view')),
                ('visible_from', models.DateTimeField(blank=True, help_text='Drop is pending/hidden until this time. null = immediately visible.', null=True)),
                ('webhook_url', models.URLField(blank=True, default='', help_text='POST to this URL on drop access. Empty = no webhook.')),
                ('notify_before_secs', models.PositiveIntegerField(blank=True, help_text='Seconds before expiry to send notification. null = no notification.', null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Visible in public feed and searchable.')),
                ('is_test', models.BooleanField(db_index=True, default=False, help_text='Created by the integration test suite. Purged at deploy.')),
                ('password_hash', models.CharField(blank=True, default='', help_text='PBKDF2 hash. Empty = no password.', max_length=256)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drops', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, help_text='Group that owns this drop (alongside or instead of user owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drops', to='core.group')),
            ],
            options={
                'unique_together': {('ns', 'key')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('writer', 'Writer'), ('admin', 'Admin')], default='reader', max_length=8)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SavedDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(choices=[('c', 'Clipboard'), ('f', 'File')], default='c', max_length=1)),
                ('key', models.CharField(max_length=120)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_drops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'ns', 'key')},
            },
        ),
    ]
