# Generated by Django 5.0.1 on 2026-02-28 03:09

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('exc_type', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('github_issue_url', models.URLField(blank=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('anon', 'Anonymous'), ('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], max_length=16, unique=True)),
                ('storage_quota', models.BigIntegerField(default=0)),
                ('max_file_size', models.BigIntegerField(default=0)),
                ('max_expiry_days', models.IntegerField(blank=True, null=True)),
                ('can_password', models.BooleanField(default=False)),
                ('can_encrypt', models.BooleanField(default=False)),
                ('can_custom_key', models.BooleanField(default=True)),
                ('folder_quota', models.IntegerField(blank=True, null=True)),
                ('helpbot_hourly', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('upload', 'Upload / download'), ('expiry', 'Expiry / deletion'), ('auth', 'Login / account'), ('billing', 'Billing'), ('ui', 'UI / display'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField()),
                ('hide_identity', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=core.models.generate_key, max_length=64, unique=True)),
                ('anon_token', models.CharField(blank=True, max_length=64)),
                ('b2_name', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('size', models.BigIntegerField(default=0)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('is_public', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('burn_after_read', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FolderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=512)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.folder')),
            ],
        ),
        migrations.CreateModel(
            name='HelpBotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helpbot_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('anon', 'Anonymous'), ('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', max_length=16)),
                ('plan_since', models.DateTimeField(blank=True, null=True)),
                ('ls_customer_id', models.CharField(blank=True, max_length=64)),
                ('ls_subscription_id', models.CharField(blank=True, max_length=64)),
                ('ls_subscription_status', models.CharField(blank=True, max_length=32)),
                ('storage_used_bytes', models.BigIntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verify_token', models.CharField(blank=True, max_length=64)),
                ('notify_product_updates', models.BooleanField(default=True)),
                ('notify_billing', models.BooleanField(default=True)),
                ('notify_bug_fix', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', '-created_at'], name='core_file_owner_i_3d0ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['expires_at'], name='core_file_expires_fc6610_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_public', '-created_at'], name='core_file_is_publ_df143e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filebookmark',
            unique_together={('user', 'file_key')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'parent', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='folderitem',
            unique_together={('folder', 'key')},
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('file', 'user'), name='unique_like_user'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('file', 'ip'), name='unique_like_ip'),
        ),
    ]
