# Generated by Django 5.0.1 on 2026-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], max_length=20, unique=True)),
                ('storage_bytes', models.BigIntegerField(help_text='Total storage in bytes')),
                ('max_file_bytes', models.BigIntegerField(help_text='Max single file size in bytes')),
                ('max_expiry_days', models.IntegerField(help_text='Max key expiry in days')),
                ('max_folders', models.IntegerField(blank=True, help_text='Max folders (null = unlimited)', null=True)),
                ('password_protected', models.BooleanField(default=False)),
                ('custom_keys', models.BooleanField(default=True)),
                ('helpbot_calls_per_hr', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'plan limits',
                'verbose_name_plural': 'plan limits',
            },
        ),
    ]
