# Generated by Django 5.0.1 on 2026-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='kind',
        ),
    ]
