# Generated by Django 5.0.1 on 2026-02-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When the expiry notification was sent. null = not yet sent.', null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='tags',
            field=models.CharField(blank=True, default='', help_text="Comma-separated tags for public discovery. e.g. 'python,snippet'.", max_length=500),
        ),
        migrations.AddField(
            model_name='featureproposal',
            name='staff_pick',
            field=models.BooleanField(default=False, help_text='Weekly staff highlight'),
        ),
    ]
