# Generated by Django 5.0.1 on 2026-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drop_notified_at_drop_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlimit',
            name='helpbot_hourly',
            field=models.PositiveIntegerField(default=0, help_text='Help bot questions per hour. 0 = disabled.'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug — something is broken'), ('ui', 'UI — visual or layout issue'), ('perf', "Performance — it's slow"), ('security', 'Security concern'), ('other', 'Other')], max_length=16),
        ),
    ]
