# Generated by Django 5.0.1 on 2026-02-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderitem',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Display name in folder path URLs. Defaults to filename or key.', max_length=255),
        ),
    ]
