# Generated by Django 5.0.1 on 2026-02-23 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_helpbot_hourly_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent collection for nesting (sub-collections).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.collection'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('owner', 'parent', 'slug')},
        ),
    ]
