# Generated by Django 5.0.1 on 2026-03-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_plan_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlimits',
            name='max_folders',
        ),
    ]
