# Generated by Django 6.0.2 on 2026-02-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_folderitem_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedDrop',
        ),
    ]
