# Generated by Django 5.0.1 on 2026-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sub_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlimit',
            name='api_fetch',
            field=models.BooleanField(default=False, help_text='Allow fetching external URLs via drp get.'),
        ),
        migrations.AddField(
            model_name='planlimit',
            name='smart_parse',
            field=models.BooleanField(default=True, help_text='Allow smart content parsing (--parse, --field).'),
        ),
    ]
