# Generated by Django 5.0.1 on 2026-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_smart_parse_api_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Live API reference. When set, drp get fetches from this URL each time.'),
        ),
    ]
