# Generated by Django 5.0.1 on 2026-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planlimit_anon_file_lifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
