# Generated by Django 5.0.1 on 2026-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_pricing_cad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique identifier, e.g. verify_email', max_length=80, unique=True)),
                ('description', models.CharField(blank=True, help_text='Admin note about where this template is used', max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField(help_text='Plain text body. Use {placeholder} for variables.')),
                ('body_html', models.TextField(blank=True, help_text='Optional HTML body. Leave blank for plain-text-only emails.')),
                ('from_email', models.EmailField(blank=True, help_text='Override from address. Blank = DEFAULT_FROM_EMAIL.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter (CA$5/mo)'), ('pro', 'Pro (CA$10/mo)')], default='free', max_length=16),
        ),
    ]
