# Generated by Django 5.0.1 on 2026-03-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('exc_type', models.CharField(max_length=255)),
                ('exc_message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('command', models.CharField(blank=True, default='', max_length=64)),
                ('cli_version', models.CharField(blank=True, default='', max_length=32)),
                ('python_version', models.CharField(blank=True, default='', max_length=32)),
                ('platform', models.CharField(blank=True, default='', max_length=128)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('issue_url', models.URLField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
